server:
  port: 81
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://****:3306/orderfood?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false"
    username: "root"
    password: ENC(YX5S7dfmLWkIR+RO73wi7A==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  redis:
    cluster:
      nodes[0]: ****:7031
      nodes[1]: ****:7032
      nodes[2]: ****:7033
      nodes[3]: ****:7034
      nodes[4]: ****:7035
      nodes[5]: ****:7036
    timeout: 10000ms
    redisson:
      config: classpath:redisson_dev.yml
  freemarker:
    check-template-location: false
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    view:
      prefix: /html/
      suffix: .html
