server:
  port: 80
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://10.3.200.4:3306/orderfood?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false"
    username: "root"
    password: ENC(YX5S7dfmLWkIR+RO73wi7A==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  freemarker:
    check-template-location: false
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    view:
      prefix: /html/
      suffix: .html
