server:
  port: 9000
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://192.168.56.102:3306/orderfood?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false"
    username: "root"
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  freemarker:
    check-template-location: false
logging:
  pattern:
    console: "%d  - [%thread] - %-5level - [%logger{50}]  - [%msg%n]  "
#  path: log/
  file: log/my.log
  level:
    root: info
#    com.mm: debug
#  pattern:
#    file: "%d{yyyy‐MM‐dd} === [%thread] === %‐5level === %logger{50} ==== %msg%n"
#    console: "%d{yyyy‐MM‐dd} [%thread] %‐5level %logger{50} ‐ %msg%n"