package com.mm.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;
import javax.persistence.Id;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Sat Nov 17 23:48:39 CST 2018.</p>
 *
 * @author 
 */

@Entity
@Data
@Slf4j
@Table ( name ="order_detail" )
public class OrderDetail  implements Serializable {


    private static final long serialVersionUID = 3048065223659541935L;

    static {
        log.info("info==--");
        log.debug("debug====");
        log.warn("warn");
        log.error("error====");
        log.trace("trace====");

    }
    @Id
   	@Column(name = "detail_id" )
	private String detailId;

   	@Column(name = "order_id" )
	private String orderId;

   	@Column(name = "product_id" )
	private String productId;

	/**
	 * 商品名称
	 */
   	@Column(name = "product_name" )
	private String productName;

	/**
	 * 当前价格,单位分
	 */
   	@Column(name = "product_price" )
	private Double productPrice;

	/**
	 * 数量
	 */
   	@Column(name = "product_quantity" )
	private Long productQuantity;

	/**
	 * 小图
	 */
   	@Column(name = "product_icon" )
	private String productIcon;

	/**
	 * 创建时间
	 */
   	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 修改时间
	 */
   	@Column(name = "update_time" )
	private Date updateTime;

}
