package com.mm.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;
import javax.persistence.Id;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Sat Nov 17 23:48:58 CST 2018.</p>
 *
 * @author 
 */
@Entity
@Data
@Slf4j
@Table ( name ="product_category" )
public class ProductCategory  implements Serializable {


	private static final long serialVersionUID =  4922061293446199604L;

    @Id
   	@Column(name = "category_id" )
	private Long categoryId;

	/**
	 * 类目名字
	 */
   	@Column(name = "category_name" )
	private String categoryName;

	/**
	 * 类目编号
	 */
   	@Column(name = "category_type" )
	private Integer categoryType;

	/**
	 * 创建时间
	 */
   	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 修改时间
	 */
   	@Column(name = "update_time" )
	private Date updateTime;

}
