package com.mm.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;
import javax.persistence.Id;
import lombok.Data;
import lombok.extern.slf4j.Slf4j;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Sat Nov 17 23:48:58 CST 2018.</p>
 *
 * @author 
 */
@Entity
@Data
@Slf4j
@Table ( name ="seller_info" )
public class SellerInfo  implements Serializable {


	private static final long serialVersionUID =  6178543964658715810L;


   	@Id
	@Column(name = "id" )
	private String id;

   	@Column(name = "username" )
	private String username;

   	@Column(name = "password" )
	private String password;

	/**
	 * 微信openid
	 */
   	@Column(name = "openid" )
	private String openid;

	/**
	 * 创建时间
	 */
   	@Column(name = "create_time" )
	private Date createTime;

	/**
	 * 修改时间
	 */
   	@Column(name = "update_time" )
	private Date updateTime;

}
